# Analytics Rules build and deploy pipeline
# This pipeline publishes the rules file as an artifact and then uses a powershell task to deploy

name: build and deploy Alert Rules

trigger:
- main

pool:
 vmImage: "windows-2019"

variables: 
- group: "az-sentinel"

steps:
- task: AzurePowerShell@5
  displayName: "Deploy anaytics rule to first workspace"
  inputs:
    ScriptType: 'FilePath'
    ScriptPath: '$(Build.SourcesDirectory)\sentinelascode\Scripts\CreateAnalyticsRules.ps1'
    ScriptArguments: ' -Workspace $(Workspace) -RulesFile $(Build.SourcesDirectory)\sentinelascode\AnalyticsRules\analytics-rules.json'
    azurePowerShellVersion: 'LatestVersion'
    pwsh: true

